### ISSUE TITLE
help template failed

### ISSUE THREAD

**Issue by ant1dot** [wrike/callisto-chart#10]
macOS 13.1

helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}

run: helm template .

and get error:

helm.go:84: [debug] template: callisto/templates/callisto-nginx-configmap.yaml:11:3: executing "callisto/templates/callisto-nginx-configmap.yaml" at <tpl (.Files.Glob "files/callisto-nginx.conf").AsConfig .>: error calling tpl: error during tpl function execution for "callisto-nginx.conf: \"upstream callisto {\\r\\n  server {{ template \\\"callisto.name\\\"\n  . }}:8080;\\r\\n}\\r\\nupstream selenoid {\\r\\n  server {{ template \\\"callisto.name\\\"\n  . }}-selenoid-ui:8000;\\r\\n}\\r\\nmap $http_upgrade $connection_upgrade {\\r\\n    default\n  upgrade;\\r\\n    ''      close;\\r\\n}\\r\\n\\r\\nlog_format custom '$remote_addr [$time_iso8601]\n  $scheme \\\"$request\\\" $request_time $status \\\"$http_user_agent\\\" $upstream_response_time\n  \\\"$host\\\" $upstream_addr \\\"{{ .Values.instanceID }}\\\"';\\r\\naccess_log off;\\r\\n\\r\\nserver\n  {\\r\\n  listen 80 default_server;\\r\\n  resolver {{ .Values.nginx.resolver }};\\r\\n\n  \\ access_log /var/log/nginx/access.log custom;\\r\\n\\r\\n  proxy_connect_timeout       600;\\r\\n\n  \\ proxy_send_timeout          600;\\r\\n  proxy_read_timeout          600;\\r\\n  send_timeout\n  \\               600;\\r\\n\\r\\n  rewrite ^(.*)/se/file$ $1/file break;  # selenium\n  4 compatibility\\r\\n\\r\\n  error_page 504 /504.html;\\r\\n    location /504.html {\\r\\n\n  \\   return 504 '{\\\"error\\\": \\\"504\\\", \\\"message\\\": \\\"Gateway Timeout at Callisto\n  nginx. Probably the browser has crashed.\\\"}';\\r\\n  }\\r\\n  error_page 503 /503.html;\\r\\n\n  \\   location /503.html {\\r\\n    return 503 '{\\\"error\\\": \\\"503\\\", \\\"message\\\": \\\"Service\n  Temporarily Unavailable at Callisto nginx. Probably the Kubernetes API is unavailable.\\\"}';\\r\\n\n  \\ }\\r\\n  error_page 502 /502.html;\\r\\n    location /502.html{\\r\\n    return 502\n  '{\\\"error\\\": \\\"502\\\", \\\"message\\\": \\\"Bad Gateway at Callisto nginx. Probably the\n  container for the browser is not running.\\\"}';\\r\\n  }\\r\\n  location ~ /session/(?<pod_name>browser-[a-z0-9]+)-(?<pod_ip>[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+)-(?<session_id>[a-z0-9-]+)/(?<tests_request>.+)\n  {\\r\\n    proxy_http_version 1.1;\\r\\n    proxy_connect_timeout       30;\\r\\n    proxy_send_timeout\n  \\         30;\\r\\n    proxy_read_timeout          30;\\r\\n    send_timeout                30;\\r\\n\n  \\   client_max_body_size        8m;\\r\\n    proxy_request_buffering off; # disable\n  request buffering on disk\\r\\n    {{- if eq .Values.callisto.browser.name \\\"firefox\\\"\n  }}\\r\\n    proxy_pass http://$pod_ip:4444{{ .Values.callisto.browser.firefoxWebdriverPath\n  }}/session/$session_id/$tests_request;\\r\\n    {{- else }}\\r\\n    proxy_pass http://$pod_ip:4444/session/$session_id/$tests_request;\\r\\n\n  \\   {{- end }}\\r\\n  }\\r\\n  location ~ /session/(?<pod_name>browser-[a-z0-9]+)-(?<pod_ip>[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+)-(?<session_id>[a-z0-9-]+)\n  {\\r\\n    proxy_http_version 1.1;\\r\\n    proxy_pass http://callisto/api/v1/session/$pod_name;\\r\\n\n  \\ }\\r\\n  location /session {\\r\\n    proxy_http_version 1.1;\\r\\n    proxy_pass http://callisto/api/v1/session;\\r\\n\n  \\ }\\r\\n  location ~ /vnc/(?<pod_name>browser-[a-z0-9]+)-(?<pod_ip>[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+)-(?<session_id>[a-z0-9-]+)\n  {\\r\\n    proxy_set_header Upgrade $http_upgrade;\\r\\n    proxy_set_header Connection\n  $connection_upgrade;\\r\\n    proxy_set_header Host $host;\\r\\n    proxy_buffering\n  off;\\r\\n    proxy_http_version 1.1;\\r\\n    proxy_pass http://$pod_ip:5900;\\r\\n  }\\r\\n\n  \\ location ~ /ws/logs/(?<pod_name>browser-[a-z0-9]+)-(?<pod_ip>[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+)-(?<session_id>[a-z0-9-]+)\n  {\\r\\n    proxy_set_header Upgrade $http_upgrade;\\r\\n    proxy_set_header Connection\n  $connection_upgrade;\\r\\n    proxy_set_header Host $host;\\r\\n    proxy_buffering\n  off;\\r\\n    proxy_http_version 1.1;\\r\\n    proxy_pass http://callisto/api/v1/logs/$pod_name;\\r\\n\n  \\ }\\r\\n  location / {\\r\\n    # selenoid-ui\\r\\n    proxy_set_header Upgrade $http_upgrade;\\r\\n\n  \\   proxy_set_header Connection $connection_upgrade;\\r\\n    proxy_set_header Host\n  $host;\\r\\n    proxy_buffering off;\\r\\n    proxy_http_version 1.1;\\r\\n    proxy_pass\n  http://selenoid/;\\r\\n  }\\r\\n  # We don't support video playback in Selenoid-UI\\r\\n\n  \\ #location ~ /callisto/video {\\r\\n  #  return 200 '{}';\\r\\n  #}\\r\\n  location ~\n  /callisto/(.*) {\\r\\n    proxy_http_version 1.1;\\r\\n    proxy_pass http://callisto/api/v1/$1;\\r\\n\n  \\ }\\r\\n  location /stub_status {\\r\\n      stub_status;\\r\\n      access_log off;\\r\\n\n  \\     allow all;\\r\\n  }\\r\\n  location /health {\\r\\n    access_log off;\\r\\n\\r\\n    return\n  200;\\r\\n  }\\r\\n}\\r\\n\"": parse error at (callisto/templates/callisto-nginx-configmap.yaml:1): unexpected "\\" in template clause

**Comment by sergusha** [comment]
Hi @ant1dot 

Are you running `helm template .` from the repo root?

Also, could you please check that you haven't added accidental character to `files/callisto-nginx.conf`

**Comment by ant1dot** [comment]
> Are you running `helm template .` from the repo root?

yes

> Also, could you please check that you haven't added accidental character to files/callisto-nginx.conf

I didn't edit the config, attached it (rename to txt)

[callisto-nginx.txt](https://github.com/wrike/callisto-chart/files/10456645/callisto-nginx.txt)

**Comment by ant1dot** [comment]
> Hi @ant1dot
> 
> Are you running `helm template .` from the repo root?
> 
> Also, could you please check that you haven't added accidental character to `files/callisto-nginx.conf`

problen in \r\n, i rewrite all files and the problem was solved
