### ISSUE TITLE
Host not found when coredns used

### ISSUE THREAD

**Issue by vilyansky** [wrike/callisto-chart#2]
In callisto-nginx-65f9c5c9bf-5plk2 logs:

>2020/08/11 15:13:24 [emerg] 1#1: host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/conf.d/callisto-nginx.conf:17
> nginx: [emerg] host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/conf.d/callisto-nginx.conf:17
When coredns used in cluster. 

In this case I suggest to parametrize reslover in nginx.conf and get it value outside to values.yaml

`diff --git a/files/callisto-nginx.conf b/files/callisto-nginx.conf`
`index ace2d72..62d4991 100644`
`--- a/files/callisto-nginx.conf`
`+++ b/files/callisto-nginx.conf`
`@@ -14,7 +14,7 @@ access_log off;`

` server {`
`   listen 80 default_server;`
`-  resolver kube-dns.kube-system.svc.cluster.local;`
`+  resolver {{ .Values.nginx.resolver }};`
`   access_log /var/log/nginx/access.log custom;`
 
`   proxy_connect_timeout       600;`
`diff --git a/values.yaml b/values.yaml`
`index 5cde516..54ce68b 100644`
`--- a/values.yaml`
`+++ b/values.yaml`
`@@ -66,6 +66,8 @@ nginx:`
`     tag: '1.17.2-alpine'`
`     pullPolicy: Always`
 
`+  resolver: coredns.kube-system.svc.cluster.local`
`+`
`   prometheusExporter:`
`     image:`
`       registry:`

`diff --git a/files/callisto-nginx.conf b/files/callisto-nginx.conf`
`index ace2d72..62d4991 100644`
`--- a/files/callisto-nginx.conf`
`+++ b/files/callisto-nginx.conf`
`@@ -14,7 +14,7 @@ access_log off;`
 
` server {`
`   listen 80 default_server;`
`-  resolver kube-dns.kube-system.svc.cluster.local;`
`+  resolver {{ .Values.nginx.resolver }};`
`   access_log /var/log/nginx/access.log custom;`
 
`   proxy_connect_timeout       600;`
`diff --git a/values.yaml b/values.yaml`
`index 5cde516..54ce68b 100644`
`--- a/values.yaml`
`+++ b/values.yaml`
`@@ -66,6 +66,8 @@ nginx:`
`     tag: '1.17.2-alpine'`
`     pullPolicy: Always`
 
`+  resolver: coredns.kube-system.svc.cluster.local`
`+`
`   prometheusExporter:`
`     image:`
`       registry:`

**Comment by srntqn** [comment]
hi, @vilyansky! Sorry for the late response.

Would you like to submit a PR to fix this issue?

**Comment by srntqn** [comment]
Closed by https://github.com/wrike/callisto-chart/commit/41b085ab37155c4709b81ef27c59a9f7145296d9
