### ISSUE TITLE
webdriver.Remote Ingress 404

### ISSUE THREAD

**Issue by Tri0L** [wrike/callisto-chart#3]
Hello.

When we use something like:
```
driver = webdriver.Remote(
    command_executor="http://callisto-ingress-domain",
)
```

We get 404 error:
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    driver = webdriver.Remote(
  File "venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.19.2</center>
</body>
</html>
```

This is because of ingress.
When selenium webdriver send request, it does not use HOST header.
Selenium webdriver just resolve hostname to ip and then working with it.
Dump of headers sent by selenium to ingress:

```
    "headers": {
        "host": "127.0.0.1:8080",
        "accept-encoding": "identity",
        "content-length": "84",
        "accept": "application/json",
        "content-type": "application/json;charset=UTF-8",
        "user-agent": "selenium/3.141.0 (python mac)"
    },
```

because of this, Ingress will not working. Ingress need a hostname to decide route and destination.
Are you using Ingress in your environment? Or just nodePort?

**Comment by srntqn** [comment]
@Tri0L hi! 

Yes, I've checked the python client library with Callisto running in Minikube and I've got the 404 error. 
But it looks like library implementation specific issue cause everything is okay with the same Callisto instance and Java client library. No issues with this code:

```java
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class WebDriverSample {

    public static void main(String[] args) {

        ChromeOptions chromeOptions = new ChromeOptions();
        WebDriver driver;
        try {
            driver = new RemoteWebDriver(new URL("http://callisto.local"), chromeOptions);
            driver.get("http://www.google.com");
            driver.quit();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }
}

```

**Comment by srntqn** [comment]
I found out that it's possible to avoid hostname resolution using custom `RemoteConnection` object. 

Something like this:

```python
from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
connection = webdriver.remote.remote_connection.RemoteConnection('http://callisto.local',
                                                                 resolve_ip=False)
driver = webdriver.Remote(
    command_executor=connection,
    options=chrome_options
)

driver.get("http://www.google.com")
driver.quit()
```

Using this code I was able to successfully create a session.

**Comment by Tri0L** [comment]
You are right! @srntqn Thanks a lot for help with it.

**Comment by flyfei-cmd** [comment]
> I found out that it's possible to avoid hostname resolution using custom `RemoteConnection` object.
> 
> Something like this:
> 
> ```python
> from selenium import webdriver
> 
> chrome_options = webdriver.ChromeOptions()
> connection = webdriver.remote.remote_connection.RemoteConnection('http://callisto.local',
>                                                                  resolve_ip=False)
> driver = webdriver.Remote(
>     command_executor=connection,
>     options=chrome_options
> )
> 
> driver.get("http://www.google.com")
> driver.quit()
> ```
> 
> Using this code I was able to successfully create a session.

hi, I have used the above code, but it indeed create a new session, but the code hangs on 
driver = webdriver.Remote(
    command_executor=connection,
    options=chrome_options
)
I can not run the driver to visit google.com

![image](https://user-images.githubusercontent.com/69850475/128010711-fb85cbc6-5bee-4d14-a076-f3708fc91a6f.png)

**Comment by flyfei-cmd** [comment]
> > I found out that it's possible to avoid hostname resolution using custom `RemoteConnection` object.
> > Something like this:
> > ```python
> > from selenium import webdriver
> > 
> > chrome_options = webdriver.ChromeOptions()
> > connection = webdriver.remote.remote_connection.RemoteConnection('http://callisto.local',
> >                                                                  resolve_ip=False)
> > driver = webdriver.Remote(
> >     command_executor=connection,
> >     options=chrome_options
> > )
> > 
> > driver.get("http://www.google.com")
> > driver.quit()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using this code I was able to successfully create a session.
> 
> hi, I have used the above code, but it indeed create a new session, but the code hangs on
> driver = webdriver.Remote(
> command_executor=connection,
> options=chrome_options
> )
> I can not run the driver to visit google.com
> 
> ![image](https://user-images.githubusercontent.com/69850475/128010711-fb85cbc6-5bee-4d14-a076-f3708fc91a6f.png)

This is my own fault, I have solved it.
